### ISSUE TITLE
Existing tutorials to link out to...

### ISSUE THREAD

**Issue by apreshill** [rstudio4edu/rmd-tutorial-workshop#2]
My link dump:

- https://debruine.github.io/tutorials/webpages.html
- https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#r_markdown_website_basics
- https://jules32.github.io/rmarkdown-website-tutorial/index.html
- http://nickstrayer.me/RMarkdown_Sites_tutorial/

**Comment by dcossyleon** [comment]
included!
